### ISSUE TITLE
Crashes on bulk convert

### ISSUE THREAD

**Issue by Conquership** [EE-modders/Empire-Earth-Studio-2#2]
EESII crashes when trying to bulk convert textures from .SST to .TGA, didnt attempt to bulk convert from .TGA to .SST.

![Screenshot 2024-04-27 180710](https://github.com/EE-modders/Empire-Earth-Studio-2/assets/137264492/261f638d-023e-4639-ab4a-4971ec05084c)

**Comment by zocker-160** [comment]
Please install the latest version, this bug should already be fixed.

**Comment by Conquership** [comment]
my fault

**Comment by Conquership** [comment]
thank you
